### ISSUE TITLE
When notifications are muted the notification still shows the hide animation

### ISSUE THREAD

**Issue by nfoert** [nfoert/circles#1]
The `hide_notification` function in `notification.js` needs to check if `notifications_muted` is true, and if so, don't add the `hide-notification` class.

Yes, this is a very simple bug and easy to solve, but hopefully this can help some people learn how to contribute to open source.

**Comment by charann29** [comment]
@nfoert  I like to contribute to this issue please assign me this issue

**Comment by nfoert** [comment]
> @nfoert I like to contribute to this issue please assign me this issue

Ok, I'd be glad to see a PR.

**Comment by charann29** [comment]
Hey @nfoert  please check the PR I have raised.

**Comment by nfoert** [comment]
Closed by [this PR](https://github.com/nfoert/circles/pull/5). Thanks @charann29!
