### ISSUE TITLE
Some Spelling mistake in README.md

### ISSUE THREAD

**Issue by vanshajgupta37** [nfoert/circles#10]
While going through the README.md, i found some spelling mistakes so please assign me this issue, and label it under Hacktoberfest.

**Comment by nfoert** [comment]
Hi, What spelling mistakes did you find?

**Comment by vanshajgupta37** [comment]
"Infrastructure" is written as "infastructure" at two places under "INSTALLATION"

**Comment by nfoert** [comment]
> "Infrastructure" is written as "infastructure" at two places under "INSTALLATION" Can i raise a PR for it? if labelled under Hacktoberfest.

Sure, thanks for catching that. The entire repo is labeled hacktoberfest so I shouldn't have to label the issue.

**Comment by vanshajgupta37** [comment]
I just raised the PR, kindly review it.

**Comment by nfoert** [comment]
Closed by #11
