### ISSUE TITLE
Recommended Community standards missing

### ISSUE THREAD

**Issue by sree-hari-s** [nfoert/circles#15]
- [x] Code of Conduct
- [x] Contributing
- [x] Security Policy
- [x] Issue Template
- [x] PR Template

![image](https://github.com/nfoert/circles/assets/48482060/1fc9dce1-b8da-48d4-9344-2b89b1aec0f4)

**Comment by nfoert** [comment]
Thank you for creating this issue and creating a CONTRIBUTING.md file. I'll continue to complete more of these tasks.

**Comment by nfoert** [comment]
Completed!
![image](https://github.com/nfoert/circles/assets/92690073/defc97e9-4386-4075-bd87-84ebc6ff0297)

Thanks for mentioning these steps.
