### ISSUE TITLE
[BUG] Log out button missing?

### ISSUE THREAD

**Issue by sree-hari-s** [nfoert/circles#23]
**Describe the bug** 
**To Reproduce**
As I couldn't find the logout button, I tried to remove my account through the admin panel, when I returned to the site there was an HTTP response stating no accounts found

**Expected behavior**
Return to the login/register page

**Comment by nfoert** [comment]
Hi, I've not created a log out button yet. The next main feature I'm adding next is going to be a menu for customizing user details, like display name, ect.
This feature will add a logout button as well.

For now, clear the cookies for Circles by following these steps in Chrome / Chromium:

Open the details for the site
 ![image](https://github.com/nfoert/circles/assets/92690073/db80890c-202a-4ec4-82ae-f1cfefd44d5a)
 
 Press the `Cookies and site details` button
![image](https://github.com/nfoert/circles/assets/92690073/3adb7c61-42ed-4429-acaa-aa7a5f8747ac)

Then `Manage cookies and site data`. Press the trash icon.
![image](https://github.com/nfoert/circles/assets/92690073/b59a12d0-13fb-41c3-b474-a591602e484d)

**Comment by nfoert** [comment]
User details and the ability to sign out was added in [this](https://github.com/nfoert/circles/commit/a99093da778f56afbb773756b9d80fb16c7488c3) commit.
