### ISSUE TITLE
Venv folder problem in .gitignore

### ISSUE THREAD

**Issue by jonascarvalh** [nfoert/circles#7]
I believe it could be something with git with Windows, can I solve it?

![issue_gitignore_venv](https://github.com/nfoert/circles/assets/79672134/abe83723-b4dd-4483-86c7-e9b9e601d351)

**Comment by nfoert** [comment]
Hi there, thanks for taking the time to set up the project for contribution. Those files are not being ignored due to the gitignore file using a folder called ".venv" but your folder is "venv" (note the ".")

**Comment by jonascarvalh** [comment]
Oh, sorry. I'll see if I can help with something else.

**Comment by nfoert** [comment]
> Oh, sorry. I'll see if I can help with something else. In my projects, I create ever "venv".

I see. That could be something changed in the documentation, writing `<name of venv>` instead of `.venv`. I'm just used to naming it .venv and didn't really thing about it :D

**Comment by jonascarvalh** [comment]
Sure, could I do this for you?

**Comment by nfoert** [comment]
> Sure, could I do this for you?

If you'd like to, go ahead

**Comment by jonascarvalh** [comment]
#13 Solves. Thank you for confidence.
Could you use the PR label for hacktoberfest-accepted?

**Comment by nfoert** [comment]
> #13 Solves. Thank you for confidence. Could you use the PR label for hacktoberfest?

Thanks for doing this. 
The entire repo is tagged with hacktoberfest so specific issues or PRs don't need the tag.
